name: 02-workflow-events
on: 
    push:
    pull_request:
    schedule:
      - cron: '*/15 * * * *'  # every 15 minutes
    workflow_dispatch:

jobs:
    echo:
      runs-on: ubuntu-latest
      steps:
        - name: "show trigger event"
          run: echo "The event that triggered this workflow is ${{ github.event_name }}"