name: 02-workflow-events
on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "show trigger event"
        run: echo "The event that triggered this workflow is ${{ github.event_name }}"