name : 04-workflow-filter
on :
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main

jobs :
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running whenever a pull request is opened or synchronized AND the target branch is main"
